#!/usr/bin/env python3
"""Merge per-ticker staged gists into the consolidated thematic pages.

Why this exists
---------------
The 3rd authored artifact (gist + summary-table row) lives on a *shared*
thematic page. When many tickers are produced in parallel, concurrent writers
clobber each other on those 10 files. So each producer instead writes a small
staging file and this tool merges them **serially**, one page at a time.

Staging file: ``.ddh-staging/{TICKER}.json``

    {
      "ticker":      "RDDT",
      "theme_page":  "software",              # docs/deep-dives/{stem}.md
      "section":     "Cloud & Enterprise Software",   # exact '## ' heading
      "sub_heading": "Data & Analytics",      # exact '### ' heading, or null
      "gist_prose":  "2-4 sentences, $ escaped as \\$ ..."
    }

Mechanical cells (rating span, Bull/Base/Bear, dates, table cells) are written
here as a first cut and then authoritatively regenerated by
``helpers/build_derived.py`` from ``docs/api/{TICKER}.json``.

Usage:
    python3 helpers/merge_staged_gists.py --dry-run     # report only
    python3 helpers/merge_staged_gists.py               # merge everything
    python3 helpers/merge_staged_gists.py RDDT VIAV     # merge a subset
"""

from __future__ import annotations

import argparse
import json
import re
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
API_DIR = ROOT / "docs" / "api"
DD_DIR = ROOT / "docs" / "deep-dives"
STAGING = ROOT / ".ddh-staging"

RATING_CLASS = {
    "BUY": "rating-buy",
    "SPEC. BUY": "rating-spec-buy",
    "HOLD": "rating-hold",
    "HOLD / SPEC.": "rating-spec-hold",
    "SELL": "rating-sell",
    "SPECULATIVE": "rating-spec",
}

EXCHANGE_TV = {
    "NYSE": "NYSE",
    "NYSEAMERICAN": "NYSEAMERICAN",
    "AMEX": "AMEX",
    "NYSE Arca": "AMEX",
    "NASDAQ": "NASDAQ",
    "NasdaqCM": "NASDAQ",
    "NASDAQ / TSX": "NASDAQ",
    "OMXSTO": "OMXSTO",
    "KRX": "KRX",
}

GIST_HEADER_RE = re.compile(r"^\*\*([A-Z0-9]{1,7}) — .*\*\*\s*$")
TARGETS_LINE_RE = re.compile(r"^\*\*Bull:\*\* .*\*\*Bear:\*\* .*$")
ROW_TICKER_RE = re.compile(r'symbol="[^":]+:([A-Z0-9]{1,7})"')
TABLE_HEADER_RE = re.compile(r"^\|\|?\s*Ticker\s*\|")
H2_RE = re.compile(r"^##\s+(.+?)\s*$")
H3_RE = re.compile(r"^###\s+(.+?)\s*$")


def esc_money(s: str) -> str:
    return re.sub(r"(?<!\\)\$", r"\\$", s)


def tv_symbol(d: dict) -> str:
    exch = d.get("exchange", "")
    prefix = EXCHANGE_TV.get(exch)
    if prefix is None:
        prefix = exch.split(" / ")[0].split()[0].upper() if exch else "NYSE"
    return f"{prefix}:{d['ticker']}"


def rating_span(rating: str) -> str:
    return f'<span class="{RATING_CLASS.get(rating, "rating-spec")}">{rating}</span>'


def target_of(d: dict, case: str) -> str:
    v = d.get(case) or {}
    return str(v.get("target", "")) if isinstance(v, dict) else ""


def table_row(d: dict) -> str:
    return (f'| <tv-ticker-tag symbol="{tv_symbol(d)}" hide-background>'
            f'</tv-ticker-tag> | {d.get("company", "")} '
            f'| {rating_span(d.get("rating", ""))} | {d.get("last_updated", "")} '
            f'| [:material-file-document: Read]({d["ticker"]}.md) |')


def gist_block(d: dict, prose: str) -> list[str]:
    t = d["ticker"]
    return [
        f'**{t} — {d.get("company", "")} · {rating_span(d.get("rating", ""))}**',
        "",
        prose.strip(),
        "",
        f'**Bull:** {esc_money(target_of(d, "bull_case"))} · '
        f'**Base:** {esc_money(target_of(d, "base_case"))} · '
        f'**Bear:** {esc_money(target_of(d, "bear_case"))}',
        "",
        f"[:material-arrow-right: Full Deep Dive]({t}.md)",
    ]


# --- page surgery -----------------------------------------------------------

def find_section(lines: list[str], heading: str, level: int) -> int:
    """Index of the '## '/'### ' line whose text equals *heading*, else -1."""
    rx = H2_RE if level == 2 else H3_RE
    want = heading.strip().casefold()
    for i, line in enumerate(lines):
        m = rx.match(line)
        if m and m.group(1).strip().casefold() == want:
            return i
    return -1


def block_end(lines: list[str], start: int, stop_at_h3: bool) -> int:
    """Index just past the block that begins at *start* (exclusive)."""
    for i in range(start + 1, len(lines)):
        if H2_RE.match(lines[i]) or (stop_at_h3 and H3_RE.match(lines[i])):
            return i
    return len(lines)


def insert_table_row(lines: list[str], d: dict, section: str,
                     log: list[str]) -> list[str]:
    t = d["ticker"]
    for line in lines:
        if line.startswith("|") and (m := ROW_TICKER_RE.search(line)) and m.group(1) == t:
            log.append(f"    row   {t}: already present, left for build_derived")
            return lines

    sec = find_section(lines, section, 2)
    search_from = sec + 1 if sec != -1 else 0
    search_to = block_end(lines, sec, stop_at_h3=False) if sec != -1 else len(lines)

    hdr = next((i for i in range(search_from, search_to)
                if TABLE_HEADER_RE.match(lines[i])), None)
    if hdr is None:  # fall back to the first table anywhere on the page
        hdr = next((i for i in range(len(lines)) if TABLE_HEADER_RE.match(lines[i])), None)
    if hdr is None:
        log.append(f"    row   {t}: NO TABLE FOUND in section {section!r} — skipped")
        return lines

    last = hdr
    for i in range(hdr + 1, len(lines)):
        if lines[i].startswith("|"):
            last = i
        else:
            break
    log.append(f"    row   {t}: inserted after line {last + 1}")
    return lines[:last + 1] + [table_row(d)] + lines[last + 1:]


def upsert_gist(lines: list[str], d: dict, prose: str, section: str,
                sub_heading: str | None, log: list[str]) -> list[str]:
    t = d["ticker"]

    # --- existing gist: replace the prose paragraph only ---
    for i, line in enumerate(lines):
        m = GIST_HEADER_RE.match(line)
        if m and m.group(1) == t:
            tgt = next((j for j in range(i + 1, min(i + 40, len(lines)))
                        if TARGETS_LINE_RE.match(lines[j])), None)
            if tgt is None:
                log.append(f"    gist  {t}: header found but no targets line — skipped")
                return lines
            log.append(f"    gist  {t}: prose refreshed (lines {i + 2}-{tgt})")
            return lines[:i + 1] + ["", prose.strip(), ""] + lines[tgt:]

    # --- new gist: append at the end of the target block ---
    anchor, stop_h3 = -1, False
    if sub_heading:
        anchor = find_section(lines, sub_heading, 3)
        stop_h3 = True
    if anchor == -1:
        anchor = find_section(lines, section, 2)
        stop_h3 = True
    if anchor == -1:
        log.append(f"    gist  {t}: section {section!r}/{sub_heading!r} not found — skipped")
        return lines

    end = block_end(lines, anchor, stop_at_h3=stop_h3)
    while end > anchor + 1 and not lines[end - 1].strip():
        end -= 1

    # Keep the page's separator convention: if the block already ends with a
    # `---` rule, the new gist goes after it and gets its own trailing rule;
    # otherwise we introduce a leading rule to separate it from its neighbour.
    if lines[end - 1].strip() == "---":
        new = [""] + gist_block(d, prose) + ["", "---"]
    else:
        new = ["", "---", ""] + gist_block(d, prose)
    where = sub_heading or section
    log.append(f"    gist  {t}: appended under {where!r} at line {end + 1}")
    return lines[:end] + new + lines[end:]


def merge_page(stem: str, items: list[dict], dry_run: bool) -> list[str]:
    page = DD_DIR / f"{stem}.md"
    log = [f"  {page.relative_to(ROOT)}"]
    if not page.exists():
        return log + [f"    ERROR: page does not exist"]

    lines = page.read_text(encoding="utf-8").split("\n")
    for st in sorted(items, key=lambda s: s["ticker"]):
        t = st["ticker"]
        jf = API_DIR / f"{t}.json"
        if not jf.exists():
            log.append(f"    {t}: docs/api/{t}.json missing — skipped")
            continue
        d = json.loads(jf.read_text(encoding="utf-8"))
        lines = insert_table_row(lines, d, st["section"], log)
        lines = upsert_gist(lines, d, st["gist_prose"], st["section"],
                            st.get("sub_heading"), log)

    if not dry_run:
        page.write_text("\n".join(lines), encoding="utf-8")
        log.append(f"    wrote {page.relative_to(ROOT)}")
    return log


def main() -> int:
    ap = argparse.ArgumentParser(description=__doc__.split("\n")[0])
    ap.add_argument("tickers", nargs="*", help="only merge these staged tickers")
    ap.add_argument("--dry-run", action="store_true", help="report, write nothing")
    args = ap.parse_args()

    if not STAGING.exists():
        print(f"no staging directory at {STAGING}", file=sys.stderr)
        return 1

    want = {t.upper() for t in args.tickers}
    staged: dict[str, list[dict]] = {}
    bad = 0
    for f in sorted(STAGING.glob("*.json")):
        try:
            st = json.loads(f.read_text(encoding="utf-8"))
        except json.JSONDecodeError as exc:
            print(f"error: {f.name} is not valid JSON: {exc}", file=sys.stderr)
            bad += 1
            continue
        missing = [k for k in ("ticker", "theme_page", "section", "gist_prose")
                   if not st.get(k)]
        if missing:
            print(f"error: {f.name} missing {', '.join(missing)}", file=sys.stderr)
            bad += 1
            continue
        if want and st["ticker"].upper() not in want:
            continue
        staged.setdefault(st["theme_page"], []).append(st)

    if not staged:
        print("nothing to merge")
        return 1 if bad else 0

    n = sum(len(v) for v in staged.values())
    print(f"merging {n} staged ticker(s) across {len(staged)} page(s)"
          + (" (dry-run)" if args.dry_run else ""))
    for stem in sorted(staged):
        print("\n".join(merge_page(stem, staged[stem], args.dry_run)))
    if bad:
        print(f"\n{bad} staging file(s) rejected", file=sys.stderr)
    return 1 if bad else 0


if __name__ == "__main__":
    sys.exit(main())
